"""Add proof_image_url and message image_url

Revision ID: 8d709bb6080f
Revises: 48325cf53ee5
Create Date: 2026-03-24 18:21:30.412980
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d709bb6080f'
down_revision = '48325cf53ee5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('POSTER', 'PERFORMER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('completed_tasks_count', sa.Integer(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance >= 0', name=op.f('ck_users_users_balance_non_negative')),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name=op.f('ck_users_users_rating_range')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_location', 'users', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_users_rating', 'users', ['rating'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_jti', sa.String(length=36), nullable=False),
    sa.Column('refresh_jti', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_auth_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('access_jti', name=op.f('uq_auth_sessions_access_jti')),
    sa.UniqueConstraint('refresh_jti', name=op.f('uq_auth_sessions_refresh_jti'))
    )
    op.create_index('idx_auth_sessions_access_jti', 'auth_sessions', ['access_jti'], unique=False)
    op.create_index('idx_auth_sessions_refresh_jti', 'auth_sessions', ['refresh_jti'], unique=False)
    op.create_index('idx_auth_sessions_revoked_at', 'auth_sessions', ['revoked_at'], unique=False)
    op.create_index('idx_auth_sessions_user_id', 'auth_sessions', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('runner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('location_lat', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('location_lng', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('initial_offer', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('accepted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('proof_image_url', sa.String(length=500), nullable=True),
    sa.Column('completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('initial_offer > 0', name=op.f('ck_tasks_tasks_initial_offer_positive')),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], name=op.f('fk_tasks_creator_id_users')),
    sa.ForeignKeyConstraint(['runner_id'], ['users.user_id'], name=op.f('fk_tasks_runner_id_users')),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_tasks'))
    )
    op.create_index('idx_tasks_category', 'tasks', ['category'], unique=False)
    op.create_index('idx_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_tasks_creator', 'tasks', ['creator_id'], unique=False)
    op.create_index('idx_tasks_location', 'tasks', ['location_lat', 'location_lng'], unique=False)
    op.create_index('idx_tasks_runner', 'tasks', ['runner_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], name=op.f('fk_messages_sender_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_messages_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_index('idx_messages_task', 'messages', ['task_id'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('runner_id', sa.UUID(), nullable=False),
    sa.Column('proposed_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('proposed_price > 0', name=op.f('ck_proposals_proposals_price_positive')),
    sa.ForeignKeyConstraint(['runner_id'], ['users.user_id'], name=op.f('fk_proposals_runner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_proposals_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proposals'))
    )
    op.create_index('idx_proposals_runner', 'proposals', ['runner_id'], unique=False)
    op.create_index('idx_proposals_status', 'proposals', ['status'], unique=False)
    op.create_index('idx_proposals_task', 'proposals', ['task_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewee_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_reviews_rating_range')),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.user_id'], name=op.f('fk_reviews_reviewee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], name=op.f('fk_reviews_reviewer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_reviews_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('task_id', 'reviewer_id', name='uq_task_reviewer')
    )
    op.create_index('idx_reviews_reviewee', 'reviews', ['reviewee_id'], unique=False)
    op.create_index('idx_reviews_reviewer', 'reviews', ['reviewer_id'], unique=False)
    op.create_index('idx_reviews_task', 'reviews', ['task_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_transactions_task_id_tasks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_transactions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    op.create_index('idx_transactions_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index('idx_transactions_task', 'transactions', ['task_id'], unique=False)
    op.create_index('idx_transactions_type', 'transactions', ['transaction_type'], unique=False)
    op.create_index('idx_transactions_user', 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_transactions_user', table_name='transactions')
    op.drop_index('idx_transactions_type', table_name='transactions')
    op.drop_index('idx_transactions_task', table_name='transactions')
    op.drop_index('idx_transactions_created_at', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('idx_reviews_task', table_name='reviews')
    op.drop_index('idx_reviews_reviewer', table_name='reviews')
    op.drop_index('idx_reviews_reviewee', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('idx_proposals_task', table_name='proposals')
    op.drop_index('idx_proposals_status', table_name='proposals')
    op.drop_index('idx_proposals_runner', table_name='proposals')
    op.drop_table('proposals')
    op.drop_index('idx_messages_task', table_name='messages')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_runner', table_name='tasks')
    op.drop_index('idx_tasks_location', table_name='tasks')
    op.drop_index('idx_tasks_creator', table_name='tasks')
    op.drop_index('idx_tasks_created_at', table_name='tasks')
    op.drop_index('idx_tasks_category', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_auth_sessions_user_id', table_name='auth_sessions')
    op.drop_index('idx_auth_sessions_revoked_at', table_name='auth_sessions')
    op.drop_index('idx_auth_sessions_refresh_jti', table_name='auth_sessions')
    op.drop_index('idx_auth_sessions_access_jti', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_rating', table_name='users')
    op.drop_index('idx_users_location', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
