"""Add reviews table

Revision ID: f34fafc035cf
Revises: 0004_proposals_and_task_pivot
Create Date: 2026-03-24 16:15:10.015517
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34fafc035cf'
down_revision = '0004_proposals_and_task_pivot'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewee_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_reviews_reviews_rating_range')),
    sa.ForeignKeyConstraint(['reviewee_id'], ['users.user_id'], name=op.f('fk_reviews_reviewee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], name=op.f('fk_reviews_reviewer_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], name=op.f('fk_reviews_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('task_id', 'reviewer_id', name='uq_task_reviewer')
    )
    op.create_index('idx_reviews_reviewee', 'reviews', ['reviewee_id'], unique=False)
    op.create_index('idx_reviews_reviewer', 'reviews', ['reviewer_id'], unique=False)
    op.create_index('idx_reviews_task', 'reviews', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reviews_task', table_name='reviews')
    op.drop_index('idx_reviews_reviewer', table_name='reviews')
    op.drop_index('idx_reviews_reviewee', table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
